#Name: Bridget Martinez
#Date: 11/29
#Course: CSC2280
#Email: bmartinez2999@gmail.com
#Assignment: Final Project


def thegame():
    endings = 0
    s= "----- CHAPTER 1 - Building up! -----"
    #begin chapter 1- press enter to go onto the next phase
    print("\033[1m" + s + "\033[0m")
    kljdfkls = input("")
    print("Our story begins on a cold december evening, it started off as a normal day at the construction site until everything turned a little strange...")
    kljdfkls = input("")
    print("After a long day of doing very important construction things, as you're walking to the office to leave you suddenly feel very, very, sleepy...")
    kljdfkls = input("")
    print("When you open your eyes you're met with darkness...")
    kljdfkls = input("")
    print("You quickly realize they had just turned all the lights off and forgotten about you... again...")
    kljdfkls = input("")
    print("As you slowly regain consiousness you hear a couple voices in the distance...")
    kljdfkls = input("")
    print("As you get closer to the voices you see three strange people who definitely dont belong in a construction zone...")
    kljdfkls = input("")
    #dialouge from the user
    print("                       You                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|       Hey, this is a hard hat only zone...        |")
    print("|                                                   |")
    print("-----------------------------------------------------")
    kljdfkls = input("")
    print("You see the three strange people slowly turn to you...")
    kljdfkls = input("")
    print("As you get closer you're able to get a better picture of the three trespassers")
    kljdfkls = input("")
    print("The tallest of the group looks to be dressed in a Lumber Jack costume in the middle of december...")
    kljdfkls = input("")
    print("You can barely make out the next one, they look like some sort of hot topic worker?...")
    kljdfkls = input("")
    print("The final one of the group looks like... your best friends dad? Thats not possible last you heard they were vacationing in Nebraska... Upon further inspection its just a very dadly looking stranger")
    kljdfkls = input("")
    print("                      You                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|          You guys really cant be here...          |")
    print("|                                                   |")
    print("-----------------------------------------------------")
    kljdfkls = input("")
    print("They all turn to you and the dad speaks...")
    kljdfkls = input("")
    print("                  Dadly Stranger                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|           We all just woke up here,               |")
    print("|      none of us know how we ended up here...      |")
    print("|                                                   |")
    print("-----------------------------------------------------")
    kljdfkls = input("")
    #used to make the next italics - symbolizing the users inner thoughts 
    text = "Thats Strange... I should probably call my boss"
    italic_text = "\x1B[3m" + text + "\x1B[0m"
    print(italic_text)
    kljdfkls = input("")
    print("As you pull out your phone you realize its dead... you could've sworn you charged it, suddenly the hottopic worker speaks...")
    kljdfkls = input("")
    print("                 Hottopic worker                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|            well how did you get here...           |")
    print("|                                                   |")
    print("-----------------------------------------------------")
    kljdfkls = input("")
    print("                       You                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|              I literally work here...             |")
    print("|                                                   |")
    print("-----------------------------------------------------")
    kljdfkls = input("")
    print("As everyone looks around trying to figure out what to do next the lumber jack finally speaks...")
    kljdfkls = input("")
    print("                   Lumber Jack                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|           Well whats your name anyways...         |")
    print("|                                                   |")
    print("-----------------------------------------------------")

    kljdfkls = input("")
    #while true to loop over entering the users name, and breaks once the user says yes to it being the correct name and prints 
    while True: 
        print("It takes you a second to remember...")
        #needs to be lowercase
        user_name = input("What is your name? ")
        print("{} are you sure?".format(user_name))
        print(">>> Yes")
        print(">>> No")
        yes_or_no = input(" ")
        if yes_or_no.isalpha() == True:
            if yes_or_no == "yes":
                print("                      {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|          my name is, {}...                        |".format(user_name))
                print("|                                                   |")
                print("-----------------------------------------------------")

                break 
            else:
                print("No... not {}".format(user_name))
    kljdfkls = input("")
    print("                   Lumber Jack                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|                  Mine is wood...                  |")
    print("|                                                   |")
    print("-----------------------------------------------------")

    kljdfkls = input("")
    text = "His name is... Wood?"
    italic_text = "\x1B[3m" + text + "\x1B[0m"
    print(italic_text)
    kljdfkls = input("")
    print("                  Dadly Stranger                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|              My name is cement...                 |")
    print("|                                                   |")
    print("-----------------------------------------------------")
    text = "These guys are messing with me right??"
    kljdfkls = input("")
    italic_text = "\x1B[3m" + text + "\x1B[0m"
    print(italic_text)
    kljdfkls = input("")
    print("                  Hottopic worker                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|                and mine is stone...               |")
    print("|                                                   |")
    print("-----------------------------------------------------")
    kljdfkls = input("")
    text = "Theres no way..."
    italic_text = "\x1B[3m" + text + "\x1B[0m"
    print(italic_text)
    kljdfkls = input("")
    print("                   {}                       ".format(user_name))
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|    Real funny guys im going to call the cops...   |")
    print("|                                                   |")
    print("-----------------------------------------------------")
    kljdfkls = input("")
    print("That statement seems to put the strangers on edge, they all look at eachother with terror")
    kljdfkls = input("")
    print("                   Cement...?                       ")
    print("-----------------------------------------------------")
    print("|                                                   |")
    print("|        Theres no need to call the cops,           |")
    print("|         vWe were all leaving anyways...           |")
    print("|                                                   |")
    print("-----------------------------------------------------")
    kljdfkls = input("")
    print("They all slowly start shuffling towards the exit...")
    kljdfkls = input("")
    print("You decide to follow them, and as you're leaving you notice a couple of materials missing...")
    kljdfkls = input("")
    text = "Strange its some Wood, Cement, and Stone..."
    italic_text = "\x1B[3m" + text + "\x1B[0m"
    print(italic_text)
    kljdfkls = input("")
    print("You hear something behind you but once you turn around...")
    kljdfkls = input("")
    print("Its nothing... You do however notice that your wrench is missing")
    kljdfkls = input("")
    s = "END OF CHAPTER 1 - Building up!"
    print("\033[1m" + s + "\033[0m")
    kljdfkls = input("")
    #begin chapter 2 
    s = "----- CHAPTER 2 - Crime time -----"
    #used to make the text bold
    print("\033[1m" + s + "\033[0m")
    print("The three strangers all go off into different directions...")
    kljdfkls = input("")
    print("Wood heads to the park...")
    kljdfkls = input("")
    print("Cement heads to the nearest hardware store...")
    kljdfkls = input("")
    print("And Stone heads in the direction of the mall...")
    kljdfkls = input("")
    #While true to loop over who you want to follow, if entered the correct name (must be lowercase)
    while True:
        print("Who do you wish to follow? ")
        print(">>> Wood")
        print(">>> Cement")
        print(">>> Stone")
        user_follow = input("")
        if user_follow == "wood" or user_follow == "cement" or user_follow == "stone":
            if user_follow == "wood":
                #begins woods route
                print("You choose to folllow wood into the nearest park...")
                kljdfkls = input("")
                print("He looks a little sad looking at all the trees...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|           Hey, Wood whats wrong...?               |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("Wood looks over at you with sadness and slowly gestures to the trees...")
                kljdfkls = input("")
                print("                      Wood                       ")
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|          Theres so many of them here...           |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("You desperatly try to get Woods mind off of the trees and you think of the perfect thing...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|         Hey, wanna go have a picnic...?           |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("Wood turns to you confused...")
                kljdfkls = input("")
                text = "Does he not know what a picnic is?"
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("You grab woods hand and lead him to the nearest grocery store...")
                kljdfkls = input("")
                print("As you arrive at the waalmart, Wood looks around in shock at the amount of people...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|      Ok so, what kind of food do you want...      |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("Wood gives you another confused look...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|      Okay... What kind of food do you like...?    |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("                      Wood                       ")
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|     Im not sure, I've never eaten before...       |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("You turn to Wood with a dumbfounded look...")
                kljdfkls = input("")
                text = "This guy is crazy..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("Eventually you leave with some fruit and sandwiches and hope its good enough...")
                kljdfkls = input("")
                print("You arrive back at the park and set up for a nice middle of the night picnic...")
                kljdfkls = input("")
                text = "God how did my life end up like this, all I wanted to do was build stuff..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("You both sit in silence while eating...")
                kljdfkls = input("")
                print("Well, you're eating Wood is more picking at the sandwich and fruits with curiosity...")
                kljdfkls = input("")
                print("You both come to a point of being finished, you're full and Wood seems to have gotten bored of the fruits...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|  Stay here Wood, Im going to throw these away...  |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("You walk away making sure to keep and eye on Wood, he still seems sad while looking at the other trees...")
                kljdfkls = input("")
                print("Unfortunately for you the only trash can around is around the corner leaving Wood out of your sight")
                kljdfkls = input("")
                print("Once you get back you realize Wood is missing...")
                kljdfkls = input("")
                text = "Oh god... he's... missing... theres no way..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("You run around desperately shouting his name...")
                kljdfkls = input("")
                print("To the other people in the park you look crazy but what matters is finding Wood before he...")
                kljdfkls = input("")
                print("Well you found him, bad news... he's got an axe and about to start cutting down the trees...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|   Wood! This is a public park you cant do that!   |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("You rush over to him but its too late... hes already cutting down a tree...")
                kljdfkls = input("")
                print("Some people have their phones out recording while others are on their phones probably calling the police...")
                kljdfkls = input("")
                print("                      Wood                       ")
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|      I'll save you my brothers and sisters!       |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                text = "Oh my god, hes actually crazy..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("You keep trying to get Wood to stop, while also trying to not get killed")
                kljdfkls = input("")
                print("The police sirens and lights in the distance confirms your fears... as you turn and look you hear a thump...")
                kljdfkls = input("")
                print("Hes done it, he really cut down a tree...")
                kljdfkls = input("")
                print("As you get whisked away in the back of a police car Wood as a smug smile on his face... You contemplate how all of this came to be...")
                kljdfkls = input("")
                print("As you wait in the holding cell ready to meet your fate, you unexpentantly see Cement also sitting there in cuffs...")
                kljdfkls = input("")
                print("By morning you're trending on the front page of every social media site as the crazy people who cut down a tree in a local park...")
            
                
            elif user_follow == "cement":
                #begins cements route
                kljdfkls = input("")
                print("You choose to follow Cement into the nearest hardware store...")
                kljdfkls = input("")
                print("As you walked into the loows you find cement in the hardware section looking at cement blocks... he looks a bit sad...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|           Hey, Cement whatcha looking at?         |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("He looks up at you with a sad expression before quickly shrugging it off")
                kljdfkls = input("")
                print("                     Cement                       ")
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|          Have you ever built a tree house?        |")
                print("|                                                   |")
                print("-----------------------------------------------------")

                kljdfkls = input("")
                text = "Did he just ask me if I've ever built a tree house?"
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                text = "Have I ever built a tree house?"
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                treehouse_make = input(" ")
                if treehouse_make == "yes":
                    #if the user has built a treehouse before 
                    print("                       {}                       ".format(user_name))
                    print("-----------------------------------------------------")
                    print("|                                                   |")
                    print("|            Yea, I think so why...?                |")
                    print("|                                                   |")
                    print("-----------------------------------------------------")
                    
                else:
                    #if the user hasn't built a tree house before
                    print("                   {}                       ".format(user_name))
                    print("-----------------------------------------------------")
                    print("|                                                   |")
                    print("|              No, I dont think so why...?          |")
                    print("|                                                   |")
                    print("-----------------------------------------------------")
                kljdfkls = input("")
                print("Cement looks to be contemplating something before finally making a decision")
                kljdfkls = input("")
                print("                       Cement                       ")
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|   Follow me, we're going to make a tee house...   |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                text = "A million questions race through my mind, whos tree are we using, whos paying, how did he know where the nearest hardware store was?"
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("As you follow behind cement who's suprisingly putting a lot of thought into the making of this tree house, you're ultimately left with more questions than answers...")
                kljdfkls = input("")
                print("You eventually arrive at the cashier who looks like she doesn't get paid enough to deal with our bs this late...")
                kljdfkls = input("")
                print("As she scans every item, and the total gets higher and higher, once we reach the end Cement turns to you gesturing for you to pay...")
                kljdfkls = input("")
                print("After a long hour and about 300 dollars, you finally have all the materials to build a tree house...")
                kljdfkls = input("")
                print("                   {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|     Where are we even going to build this?        |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("Cement slowly turns to you with a smile...")
                kljdfkls = input("")
                print("Cement runs off and leaves you to sit on a bench wondering how this all came to be...")
                kljdfkls = input("")
                print("Cement eventually comes back with an even bigger smile than oringally...")
                kljdfkls = input("")
                print("                       Cement                       ")
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|          Wait here, I'll find a good one          |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("You follow Cement into a gated neighborhood, no clue how he managed to get in, and into a strangers back yard...")
                kljdfkls = input("")
                print("In front of you is the most magnificent looking tree...")
                kljdfkls = input("")
                print("                   {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|   Cement this is some random persons backyard...  |")
                print("|                We cant be here                    |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("It seems like Cement has already set his mind on building it on this tree, and for some reason you agree to join him...")
                kljdfkls = input("")
                print("As you start building this treehouse in a random backyard you see a light turn on in the house...")
                kljdfkls = input("")
                print("You gestures to Cement at the light but you realize its a bit too late for that...")
                kljdfkls = input("")
                print("You hear sirens and see flashing lights in the distance...")
                kljdfkls = input("")
                print("Everything happens so fast and suddenly you're being whisked off in a police car...")
                kljdfkls = input("")
                text = "You beg the family not to press charges, they reluctantly agree... "
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                text = "You and Cement are held in a holding cell overnight where you run into Wood, confused as to how you got to this point in life you sleep until morning..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
            
            else:
                #begins stones route 
                print("You decide to follow Stone to the nearest mall, which just happends to be open 24 hours...")
                kljdfkls = input("")
                print("As you enter the building you realize finding him might be harder than expected...")
                kljdfkls = input("")
                print("Who are you kidding it'll be simple to find him...")
                kljdfkls = input("")
                print("Just as expected you find him in the hottopic looking at a new pair of black pants...")
                kljdfkls = input("")
                print("As you aproch him you notice the worker glaring at Stone...")
                kljdfkls = input("")
                text = "Great hes already caused some sort of trouble..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|                Hey, Stone...                      |")
                print("|    why is the cashier glaring daggers at you...   |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("Stone turns to you with a confused looking expression")
                kljdfkls = input("")
                print("                       Stone                         ")
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("| All I did was walk out with these cool pants...   |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|           Did you pay for them first...           |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("Stone turns to you with an even more confused look...")
                kljdfkls = input("")
                text = "Don't tell me he tried to shoplift those pants..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("                       Stone                         ")
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|  I dont know what that means but no i didn't...   |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                text = "Oh my god he tried to shop lift the pants..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("| No wonder shes glaring, You have to pay first...  |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("You sit dumbfounded at stone...")
                kljdfkls = input("")
                text = "How does the not know about paying...?"
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("You take the pants up to the cashier, her glare softens a bit when she realizes you actually want to pay for them...")
                kljdfkls = input("")
                print("You and Stone walk out of the store, you down 30 dollars and Stone gained another pair of pants...")
                kljdfkls = input("")
                print("As you guys walk around the mall, Stone spots one of those win a car scams...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|     Those are scams, no one ever wins them...     |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("Despite breaking the news to Stone he doesn't seem to care and keeps looking at the car with awe...")
                kljdfkls = input("")
                print("You basically pull stone away from the car and keep walking around the mall, every time you guys pass the car Stone's eyes immediately latch on...")
                kljdfkls = input("")
                print("Eventually you guys end up at the food court...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|           You want anything to eat...?            |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("Stone looks at you with a puzzeled look...")
                kljdfkls = input("")
                print("                       Stone                         ")
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|      I dont think i've ever eaten before...       |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                text = "Theres no way hes never eaten before... This guy really is crazy"
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|   Okaaaay, wait here I'll get us some food...     |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("You walk over to the chinese food stall that almost every mall has...")
                kljdfkls = input("")
                print("You get the most popular choice and return to Stone... Suprizingly...")
                kljdfkls = input("")
                print("Hes still there... Right where you told him to stay...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|                Here eat this...                   |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("While you eat the food, Stone seems to be picking at it with confusion... You just brush it off")
                kljdfkls = input("")
                print("Once both of you guys reach a stopping point while eating you get up to throw away the trash...")
                kljdfkls = input("")
                print("                     {}                       ".format(user_name))
                print("-----------------------------------------------------")
                print("|                                                   |")
                print("|         Stay here, I'll be right back...          |")
                print("|                                                   |")
                print("-----------------------------------------------------")
                kljdfkls = input("")
                print("As you throw away the food and return to the table, you notice... Stone is gone...")
                kljdfkls = input("")
                text = "Oh god, not again..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("You run all over the mall trying to find Stone...")
                kljdfkls = input("")
                print("You arrive at the hottopic to find an empty store... even the cashier is gone...")
                kljdfkls = input("")
                print("As you run you hear yelling from accross the mall...")
                kljdfkls = input("")
                text = "Please god tell me thats not him..."
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("As you arrive to the... scam car, you see Stone in the front seat...")
                kljdfkls = input("")
                print("He puts the car in drive and off he goes...")
                kljdfkls = input("")
                text = "Why'd they even keep the keys in the car with a full tank of gas in the middle of the mall??"
                italic_text = "\x1B[3m" + text + "\x1B[0m"
                print(italic_text)
                kljdfkls = input("")
                print("You have no time to think as you see Stone speed off, and not soon after a group of police behind him...")
                kljdfkls = input("")
                print("You sit on a bench outside of the mall just processing everything you just went through...")
                kljdfkls = input("")
                print("Eventually you call an uber home and fall asleep trying to forget about the events of the night...")
                kljdfkls = input("")
                print("As you wake up you turn the news on just to see a mug shot of Stone, suprisingly with minimal wounds on his face...")
                kljdfkls = input("")
                print("As you keep listening you hear hes being taken to federal prison... Seems hes really not a good driver...")  
            break
        elif user_follow == "wrench":
            #hidden easter egg, my roommate wanted a character to be named wrench. If i wanted to flesh this out a bit more could add the char as a secret hidden ending
            print("How... you shouldn't know of them yet")
        
        else:
            #if the user enters a wrong option
            print("I gave you three option and you choose none of them...")
    return
    
        
#beginning with the start screen
#Begin "Press Enter to start"
#Chapter Select
#Exit
while True:
    #loops over the start menu 
        print("------------- Welcome to! -------------")
        print(" >>> Press Enter")
        kljdfkls = input("")
        s = "            Build That Crime !         "
        print("\033[1m" + s + "\033[0m")
        print("-- Choose from the following options --")
        print("-------------- 1 - Begin --------------")
        print("------------- 2 - Exit :( -------------")
        user_choice = int(input("Enter your choice here: "))

        if user_choice == 1 or user_choice == 2 or user_choice == 3:
            if user_choice == 1:
                # User chooses to begin
                # goes throught the starting dialouge with choices and ends when they reach a final point with the character
                #uses a function to recall thegame and plays that out 
                print(thegame())
            else:
                # User choose to exit :(
                print("Have a good day!") 
            
        else:
            print("Invalid answer please choose 1 or 2")
    
    
    
